name       : gnome-tweaks
version    : 40.0
release    : 34
source     :
    - https://download.gnome.org/sources/gnome-tweaks/40/gnome-tweaks-40.0.tar.xz : f95f3fe031b0b01c02f79a1659f889152d3772ae3e44df8403d1460ba5eec36a
homepage   : https://wiki.gnome.org/action/show/Apps/GnomeTweakTool
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : A tool to customize advanced GNOME 3 options.
description: |
    A tool to customize advanced GNOME 3 options.
replaces   :
    - gnome-tweak-tool
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(python3)
rundeps    :
    - libhandy
    - python-gobject
setup      : |
    %patch -p1 < $pkgfiles/0001-Don-t-show-extensions-notice.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
