name       : gnome-tweak-tool
version    : 3.24.0
release    : 15
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-tweak-tool/3.24/gnome-tweak-tool-3.24.0.tar.xz : 930b248e40db4c10991978f28b46207d6d11aa938b67b36abc68dbc7d37f1e00
homepage   : https://wiki.gnome.org/action/show/Apps/GnomeTweakTool
license    : GPL-3.0
component  : desktop.gnome
summary    : A tool to customize advanced GNOME 3 options.
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(python-3.5)
rundeps    :
    - python3-gobject
description: |
    A tool to customize advanced GNOME 3 options.
setup      : |
    %patch -p1 < $pkgfiles/0001-Ensure-settings.ini-directory-exists-before-writing-.patch
    %patch -p1 < $pkgfiles/0001-Switch-to-Python-3.patch
    %configure
build      : |
    %make
install    : |
    %make_install
