name       : gnome-tweak-tool
version    : 3.22.0
release    : 13
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-tweak-tool/3.22/gnome-tweak-tool-3.22.0.tar.xz : 3d6ae11e13f6169ee543e573135e1e5697cf92ab8d86570c6f952021ae093abb
homepage   : https://wiki.gnome.org/action/show/Apps/GnomeTweakTool
license    : GPL-3.0
component  : desktop.gnome
summary    : A tool to customize advanced GNOME 3 options.
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(gtk+-3.0)
description: |
    A tool to customize advanced GNOME 3 options.
setup      : |
    %patch -p1 < $pkgfiles/0001-Ensure-settings.ini-directory-exists-before-writing-.patch
    %configure
build      : |
    %make
install    : |
    %make_install
