name       : gnome-tweak-tool
version    : 3.26.3
release    : 20
source     :
    - https://download.gnome.org/sources/gnome-tweak-tool/3.26/gnome-tweak-tool-3.26.3.tar.xz : 9406447850b14de204f9c5a6eaa6b63ba805ddb1a10fd863239841090af76430
homepage   : https://wiki.gnome.org/action/show/Apps/GnomeTweakTool
license    : GPL-3.0
component  : desktop.gnome
summary    : A tool to customize advanced GNOME 3 options.
description: |
    A tool to customize advanced GNOME 3 options.
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(python3)
rundeps    :
    - python3-gobject
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
