name       : gnome-tweak-tool
version    : 3.26.2
release    : 18
source     :
    - https://download.gnome.org/sources/gnome-tweak-tool/3.26/gnome-tweak-tool-3.26.2.tar.xz : 5ee2123bf7029adfe97bdf3bc11039e035b92e65acf6664655d2ddd80c1f8f9f
homepage   : https://wiki.gnome.org/action/show/Apps/GnomeTweakTool
license    : GPL-3.0
component  : desktop.gnome
summary    : A tool to customize advanced GNOME 3 options.
description: |
    A tool to customize advanced GNOME 3 options.
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(python-3.5)
rundeps    :
    - python3-gobject
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
