name       : gnome-tweak-tool
version    : 3.24.1
release    : 17
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-tweak-tool/3.24/gnome-tweak-tool-3.24.1.tar.xz : 19226b374148d660330af9a8341087c2f869bb24355f4dcc87857169eca9f565
homepage   : https://wiki.gnome.org/action/show/Apps/GnomeTweakTool
license    : GPL-3.0
component  : desktop.gnome
summary    : A tool to customize advanced GNOME 3 options.
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(python-2.7)
rundeps    :
    - python-gobject
description: |
    A tool to customize advanced GNOME 3 options.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
