name       : gnome-tweaks
version    : 3.32.0
release    : 31
source     :
    - https://download.gnome.org/sources/gnome-tweaks/3.32/gnome-tweaks-3.32.0.tar.xz : a54061b2c9150567ff22874c0c3a9e36c04ab6b0093b738c662e92c15919f90c
homepage   : https://wiki.gnome.org/action/show/Apps/GnomeTweakTool
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : A tool to customize advanced GNOME 3 options.
description: |
    A tool to customize advanced GNOME 3 options.
replaces   :
    - gnome-tweak-tool
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(python3)
rundeps    :
    - python-gobject
setup      : |
    %patch -p1 < $pkgfiles/0001-Ensure-support-for-GNOME-40-drop-Extensions-support-d.patch
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
